"""add_search_vector_and_index

Revision ID: e6fc827a35f9
Revises: 2994863bb50d
Create Date: 2026-08-29 23:10:38.938849

Note: Alembic successfully auto-generated the Computed search_vector column and GIN index.
Verified for compatibility with PostgreSQL tsvector GENERATED ALWAYS AS STORED.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6fc827a35f9'
down_revision: Union[str, Sequence[str], None] = '2994863bb50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title,'') || ' ' || coalesce(scope,''))", persisted=True), nullable=True))
    op.create_index('idx_standards_search_vector', 'standards', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_standards_search_vector', table_name='standards', postgresql_using='gin')
    op.drop_column('standards', 'search_vector')
    # ### end Alembic commands ###
